In [1]:
# Drive Mount
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import os
# to read the path of file and directory and directory
from skimage.io import imread
# used for reading image
from sklearn.model_selection import train_test_split
from skimage.transform import resize
# to resize the images so that all images are in equal size

In [ ]:
os.listdir('/content/drive/MyDrive/Deep_Learning')


['dataset.zip']

In [ ]:
!pwd

/content


In [4]:
os.listdir('/content/drive/MyDrive/Deep_Learning/cat_dog_dataset')

['dog', 'cat']

In [5]:
os.listdir('/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/cat')

['cat.83.jpg',
 'cat.30.jpg',
 'cat.8.jpg',
 'cat.29.jpg',
 'cat.60.jpg',
 'cat.34.jpg',
 'cat.74.jpg',
 'cat.67.jpg',
 'cat.56.jpg',
 'cat.9.jpg',
 'cat.55.jpg',
 'cat.28.jpg',
 'cat.57.jpg',
 'cat.40.jpg',
 'cat.27.jpg',
 'cat.19.jpg',
 'cat.12.jpg',
 'cat.47.jpg',
 'cat.4.jpg',
 'cat.45.jpg',
 'cat.26.jpg',
 'cat.81.jpg',
 'cat.43.jpg',
 'cat.80.jpg',
 'cat.77.jpg',
 'cat.52.jpg',
 'cat.48.jpg',
 'cat.31.jpg',
 'cat.21.jpg',
 'cat.68.jpg',
 'cat.79.jpg',
 'cat.59.jpg',
 'cat.70.jpg',
 'cat.3.jpg',
 'cat.85.jpg',
 'cat.63.jpg',
 'cat.37.jpg',
 'cat.71.jpg',
 'cat.89.jpg',
 'cat.11.jpg',
 'cat.82.jpg',
 'cat.38.jpg',
 'cat.84.jpg',
 'cat.15.jpg',
 'cat.20.jpg',
 'cat.7.jpg',
 'cat.75.jpg',
 'cat.46.jpg',
 'cat.22.jpg',
 'cat.78.jpg',
 'cat.90.jpg',
 'cat.62.jpg',
 'cat.32.jpg',
 'cat.51.jpg',
 'cat.36.jpg',
 'cat.72.jpg',
 'cat.87.jpg',
 'cat.41.jpg',
 'cat.10.jpg',
 'cat.88.jpg',
 'cat.33.jpg',
 'cat.42.jpg',
 'cat.53.jpg',
 'cat.17.jpg',
 'cat.1.jpg',
 'cat.54.jpg',
 'cat.58.jpg',
 

In [6]:
os.listdir('/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/dog')
# o/p is in list

['dog.50.jpg',
 'dog.37.jpg',
 'dog.41.jpg',
 'dog.35.jpg',
 'dog.16.jpg',
 'dog.46.jpg',
 'dog.23.jpg',
 'dog.48.jpg',
 'dog.51.jpg',
 'dog.12.jpg',
 'dog.44.jpg',
 'dog.64.jpg',
 'dog.31.jpg',
 'dog.13.jpg',
 'dog.59.jpg',
 'dog.9.jpg',
 'dog.43.jpg',
 'dog.20.jpg',
 'dog.57.jpg',
 'dog.71.jpg',
 'dog.67.jpg',
 'dog.66.jpg',
 'dog.36.jpg',
 'dog.28.jpg',
 'dog.8.jpg',
 'dog.19.jpg',
 'dog.63.jpg',
 'dog.29.jpg',
 'dog.30.jpg',
 'dog.11.jpg',
 'dog.7.jpg',
 'dog.62.jpg',
 'dog.53.jpg',
 'dog.45.jpg',
 'dog.69.jpg',
 'dog.72.jpg',
 'dog.60.jpg',
 'dog.65.jpg',
 'dog.47.jpg',
 'dog.61.jpg',
 'dog.38.jpg',
 'dog.68.jpg',
 'dog.56.jpg',
 'dog.34.jpg',
 'dog.6.jpg',
 'dog.24.jpg',
 'dog.21.jpg',
 'dog.15.jpg',
 'dog.54.jpg',
 'dog.4.jpg',
 'dog.1.jpg',
 'dog.58.jpg',
 'dog.42.jpg',
 'dog.70.jpg',
 'dog.22.jpg',
 'dog.39.jpg',
 'dog.3.jpg',
 'dog.14.jpg',
 'dog.26.jpg',
 'dog.33.jpg',
 'dog.52.jpg',
 'dog.17.jpg',
 'dog.25.jpg',
 'dog.32.jpg',
 'dog.2.jpg',
 'dog.40.jpg',
 'dog.49.jpg',
 'd

In [7]:
# len of images
len(os.listdir('/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/dog'))

72

In [8]:
len(os.listdir('/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/cat'))

90

In [9]:
# catpath=os.path.join('/content/content/cat_dog_dataset','cat')
# joining paths to define the cats path
for i in os.listdir('/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/cat'):
  print(i)

cat.83.jpg
cat.30.jpg
cat.8.jpg
cat.29.jpg
cat.60.jpg
cat.34.jpg
cat.74.jpg
cat.67.jpg
cat.56.jpg
cat.9.jpg
cat.55.jpg
cat.28.jpg
cat.57.jpg
cat.40.jpg
cat.27.jpg
cat.19.jpg
cat.12.jpg
cat.47.jpg
cat.4.jpg
cat.45.jpg
cat.26.jpg
cat.81.jpg
cat.43.jpg
cat.80.jpg
cat.77.jpg
cat.52.jpg
cat.48.jpg
cat.31.jpg
cat.21.jpg
cat.68.jpg
cat.79.jpg
cat.59.jpg
cat.70.jpg
cat.3.jpg
cat.85.jpg
cat.63.jpg
cat.37.jpg
cat.71.jpg
cat.89.jpg
cat.11.jpg
cat.82.jpg
cat.38.jpg
cat.84.jpg
cat.15.jpg
cat.20.jpg
cat.7.jpg
cat.75.jpg
cat.46.jpg
cat.22.jpg
cat.78.jpg
cat.90.jpg
cat.62.jpg
cat.32.jpg
cat.51.jpg
cat.36.jpg
cat.72.jpg
cat.87.jpg
cat.41.jpg
cat.10.jpg
cat.88.jpg
cat.33.jpg
cat.42.jpg
cat.53.jpg
cat.17.jpg
cat.1.jpg
cat.54.jpg
cat.58.jpg
cat.65.jpg
cat.35.jpg
cat.49.jpg
cat.64.jpg
cat.23.jpg
cat.14.jpg
cat.50.jpg
cat.39.jpg
cat.2.jpg
cat.13.jpg
cat.6.jpg
cat.66.jpg
cat.61.jpg
cat.5.jpg
cat.76.jpg
cat.25.jpg
cat.44.jpg
cat.18.jpg
cat.69.jpg
cat.16.jpg
cat.86.jpg
cat.73.jpg
cat.24.jpg


In [11]:
flat_data_arr=[]
# i/p samples
target_arr=[]
# to collect output samples
categories=['cat','dog']
datadir='/content/drive/MyDrive/Deep_Learning/cat_dog_dataset'


In [12]:
for i in categories:
    print("Loading category..........")
    path = os.path.join(datadir, i)
    for j in os.listdir(path):
        # Check if 'j' is a file before trying to read it
        if os.path.isfile(os.path.join(path, j)):
            img_arr = imread(os.path.join(path, j))
            img_resize = resize(img_arr, (150, 150, 3))
            flat_data_arr.append(img_resize.flatten())
            target_arr.append(categories.index(i))
    print("Loaded completely", i)

Loading category..........
Loaded completely cat
Loading category..........
Loaded completely dog


In [13]:
flat_data=np.array(flat_data_arr)
target_data=np.array(target_arr)

In [14]:
df=pd.DataFrame(flat_data_arr)
df.shape

(162, 67500)

In [15]:
df['Target']=target_data
df.shape

(162, 67501)

In [16]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


In [18]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0])

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_predict,y_test)


0.5151515151515151

In [20]:
df

0         1         2         3         4         5         6  \
0    0.210007  0.175332  0.153479  0.272972  0.204681  0.112182  0.296660   
1    0.266514  0.270436  0.278279  0.281895  0.285817  0.293660  0.320151   
2    0.154480  0.091735  0.103500  0.169038  0.106293  0.117328  0.167667   
3    0.286275  0.301961  0.305882  0.286220  0.301906  0.305827  0.281501   
4    0.114136  0.094528  0.082763  0.124316  0.104708  0.092944  0.137856   
..        ...       ...       ...       ...       ...       ...       ...   
157  0.309764  0.352798  0.360641  0.102719  0.142712  0.150583  0.063985   
158  0.612096  0.506214  0.470920  0.568027  0.467242  0.437046  0.544847   
159  0.562609  0.466070  0.253184  0.531096  0.417403  0.202458  0.519534   
160  0.530957  0.512927  0.380928  0.472999  0.465529  0.334881  0.398747   
161  0.458653  0.507357  0.442993  0.767779  0.813413  0.764808  0.833987   

            7         8         9  ...     67491     67492     67493  \
0    0.213734  0.147602  0.264994  ...  0.921297  0.938155  0.992966   
1    0.324072  0.331915  0.285575  ...  0.700854  0.737246  0.795792   
2    0.104989  0.107658  0.153240  ...  0.386023  0.368375  0.356778   
3    0.297187  0.301109  0.278426  ...  0.870170  0.837198  0.859041   
4    0.118248  0.106484  0.156410  ...  0.681843  0.646549  0.658314   
..        ...       ...       ...  ...       ...       ...       ...   
157  0.097519  0.108052  0.073972  ...  0.312605  0.183134  0.051387   
158  0.447135  0.420694  0.409511  ...  0.395262  0.348204  0.348204   
159  0.393667  0.170831  0.488835  ...  0.389573  0.366044  0.318985   
160  0.399377  0.304621  0.251644  ...  0.486232  0.565644  0.237841   
161  0.875909  0.851280  0.602511  ...  0.406362  0.425970  0.269107   

        67494     67495     67496     67497     67498     67499  Target  
0    0.834832  0.849279  0.960463  0.770696  0.780097  0.923214       0  
1    0.686285  0.733270  0.788196  0.676392  0.726043  0.779649       0  
2    0.370647  0.342864  0.333848  0.356371  0.347214  0.332845       0  
3    0.854953  0.819037  0.837135  0.837941  0.792424  0.803063       0  
4    0.587697  0.552403  0.564167  0.468458  0.433163  0.444928       0  
..        ...       ...       ...       ...       ...       ...     ...  
157  0.296112  0.174136  0.061359  0.305794  0.184225  0.071002       1  
158  0.372594  0.325535  0.325535  0.386530  0.339471  0.339471       1  
159  0.392066  0.368537  0.321478  0.393571  0.370042  0.322983       1  
160  0.337569  0.418725  0.168118  0.362746  0.453919  0.210229       1  
161  0.360144  0.379780  0.221999  0.454469  0.476446  0.308656       1  

[162 rows x 67501 columns]

In [23]:
path1='/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/cat/cat.10.jpg'
img=imread(path1)
# plt.imshow(img)
# plt.show()
img_resize=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img_resize)

array([0])

In [24]:
path2='/content/drive/MyDrive/Deep_Learning/cat_dog_dataset/dog/dog.11.jpg'
img=imread(path2)
img_resize=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img_resize)

array([1])